#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Rutas para el controlador usuario
user:
    path: /user
    controller: App\Controller\UserController::index

user_lista:
    path: /user/lista
    controller: App\Controller\UserController::lista

user_show:
    path: /user/show
    controller: App\Controller\UserController::show

user_create:
  path: /user/create
  controller: App\Controller\UserController::create
  methods: [POST]

user_login:
  path: /user/login
  controller: App\Controller\UserController::login
  methods: [POST]

#Rutas para el controlador video
video:
  path: /video
  controller: App\Controller\VideoController::index

video_lista:
  path: /video/lista
  controller: App\Controller\VideoController::lista

video_show:
  path: /video/show
  controller: App\Controller\VideoController::show
