#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Rutas para el controlador usuario
user:
    path: /user
    controller: App\Controller\UserController::index

#Rutas para el controlador video
video:
  path: /video
  controller: App\Controller\VideoController::index
