#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Rutas para el controlador usuario
user:
    path: /user
    controller: App\Controller\UserController::index

user_lista:
    path: /user/lista
    controller: App\Controller\UserController::lista

user_show:
    path: /user/show
    controller: App\Controller\UserController::show

user_create:
  path: /user/create
  controller: App\Controller\UserController::create
  methods: [POST]

user_login:
  path: /user/login
  controller: App\Controller\UserController::login
  methods: [POST]

user_edit:
  path: /user/edit
  controller: App\Controller\UserController::edit
  methods: [PUT]

#Rutas para el controlador video
video:
  path: /video
  controller: App\Controller\VideoController::index

video_list:
  path: /video/list
  controller: App\Controller\VideoController::list
  methods: [GET]

video_detail:
  path: /video/detail/{id}
  controller: App\Controller\VideoController::detail
  methods: [GET]

video_show:
  path: /video/show
  controller: App\Controller\VideoController::show

video_create:
  path: /video/create
  controller: App\Controller\VideoController::create
  methods: [POST]

video_remove:
  path: /video/remove/{id}
  controller: App\Controller\VideoController::remove
  methods: [DELETE]
